### ISSUE TITLE
Connect to replicas with FQDN

### ISSUE THREAD

**Issue by Kaneraz** [factset/AgDatabaseMove#21]
When we connect to replicas with SSL we'll need to use the fully qualified domain name to match the certificate, but the replica server name we get from the AG is just the server name. We should be able to use `System.Net.Dns.GetHostEntry("hostname").HostName` to get the fqdn.

**Comment by Kaneraz** [comment]
This should be resolved in #23

**Comment by alexirion10** [comment]
This does not work with named instances
