### ISSUE TITLE
Add ability to temporally limit backup window in BackupChain

### ISSUE THREAD

**Issue by Martin11175** [factset/AgDatabaseMove#36]
Currently a `BackupChain` initialised for a database on an availability group lists the most recent backups as those with the latest LSN.
However in the event where a database was restored to a server causing a discontinuation of LSNs, it is possible that the old backup may have a higher LSN than the new one, causing the old backup to be recognised as the "most recent" to restore moving forwards.
To avoid this, the tool should be configurable to take time as a parameter of how recent a backup is rather than just LSN.
That, or perhaps we could recognise a break in the LSN ordering (i.e. more recent with lower LSN) and discount those from before that point?

**Comment by alexirion10** [comment]
most of this fixed in https://github.com/factset/AgDatabaseMove/pull/110
