### ISSUE TITLE
Edit failure strategy when there are no backups

### ISSUE THREAD

**Issue by AdityaNPL** [factset/AgDatabaseMove#60]
Right now it errors in this function call:
https://github.com/factset/AgDatabaseMove/blob/683f409bf8d9565af2ec824eb84ce923225b0a4b/src/BackupChain.cs#L28

on this Linq expression:
https://github.com/factset/AgDatabaseMove/blob/683f409bf8d9565af2ec824eb84ce923225b0a4b/src/BackupChain.cs#L61-L62

like this:
```csharp
System.InvalidOperationException
Sequence contains no elements
```
--- 

We could fail this more gracefully, by adding  a few checks and chaining it with a more informative Exception?
OR we can recover by just setting `_orderedBackups = new List<BackupMetadata>()`?

I'm not sure which would be the preferred choice.
If I had to choose, I would go for the more informative exception - then the users can handle this error any which way they want.

What do you guys think?
@alexirion10 @Kaneraz

**Comment by alexirion10** [comment]
@AdityaNPL - yep Exception type would be preferred to an empty list

**Comment by AdityaNPL** [comment]
ended up fixing this with a quick exception here: https://github.com/factset/AgDatabaseMove/pull/62/commits/e792938604da67adadb04c369f09329952748380

Hit the problem when I was testing, so I thought I would add it to the same PR

**Comment by AdityaNPL** [comment]
Fixed in the above mentioned PR
