### ISSUE TITLE
BackupChain query using @@servername issue

### ISSUE THREAD

**Issue by alexirion10** [factset/AgDatabaseMove#79]
In PR https://github.com/factset/AgDatabaseMove/pull/75/files using @@servername prevents a BackupChain from being retrieved _after_  being restored from a backup on another server

**Comment by AdityaNPL** [comment]
Will take a look, maybe we can parameterise the filter to be customisable.
Or maybe there is another way to achieve the same result we are after without `@@servername`

Will update once I have some more info

**Comment by AdityaNPL** [comment]
This was reverted and fixed by matching the LSNs instead:
https://github.com/factset/AgDatabaseMove/pull/103
