### ISSUE TITLE
Server::Restore cannot restore striped backups

### ISSUE THREAD

**Issue by alexirion10** [factset/AgDatabaseMove#91]
striped backup's fail because the forloop attempts to restore on each backupMedia file

**Comment by AdityaNPL** [comment]
Looks like something like this could work if we were using T-SQL
```sql
RESTORE DATABASE [db] FROM  
DISK = N'C:\db_1.bak',  
DISK = N'C:\db_2.bak',  
DISK = N'C:\db_3.bak',  
DISK = N'C:\db_4.bak',  
WITH  FILE = 1,  NOUNLOAD,  STATS = 10
GO
```
https://www.mssqltips.com/sqlservertip/1941/striping-sql-server-database-backups/

But looks like we are using the `Restore` class - need to dig into that
https://github.com/factset/AgDatabaseMove/blob/48bb272c233e3b820518ac28e898aa2f6631674a/src/SmoFacade/Server.cs#L225

**Comment by alexirion10** [comment]
I wouldn't say "cluster" is the right description here, perhaps group?  but yes, that example TSQL looks correct.
I ran into a problem where if the full backup is stripped, but you only restore a part of the striped backup, it errors out
